
# Upgrade the system
- name: Update all packages to the latest version
  apt:
    update_cache: yes
    cache_valid_time: 600
    upgrade: dist
  tags: upd

# Disable IPv6
- name: Disable sysctl net.ipv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  tags: ipv6

# Install java ecosystem and related
- name: Install Java and Maven
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "openjdk-{{ java_version }}-jdk"
    - maven
  tags: java
