# HDFS service
- name: start hdfs
  service:
    name: hdfs
    state: started
    enabled: yes
  tags: hdfs

- name: stop hdfs
  service:
    name: hdfs
    state: stopped
    enabled: yes
  tags: hdfs

- name: retart hdfs
  service:
    name: hdfs
    state: restarted
    enabled: yes
  tags: hdfs

# Spark service (master)
- name: start spark-master
  service:
    name: spark-master
    state: started
    enabled: yes
    daemon_reload: yes
  tags: spark

- name: stop spark-master
  service:
    name: spark-master
    state: stopped
    enabled: no
    tags: spark

- name: restart spark-master
  service:
    name: spark-master
    state: restarted
    enabled: yes
  tags: spark

# Spark service (worker)
- name: start spark-worker
  service:
    name: spark-worker
    state: started
    enabled: yes
    daemon_reload: yes
  tags: spark

- name: stop spark-worker
  service:
    name: spark-worker
    state: stopped
    enabled: no
  tags: spark

- name: restart spark-worker
  service:
    name: spark-worker
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags: spark
