#### Master Security Groups rules ####

  - name: Create cluster SSH for remote access
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name }}-master"
      start_port: 22
      end_port: 22
      cidr: "{{ cluster_ssh_cidr }}"
    tags: sgr

# Master Spark rules


#### Worker Security Groups rules #####

  - name: Create cluster SSH for remote access
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}-worker"
      start_port: 22
      end_port: 22
      cidr: "{{ cluster_ssh_cidr }}"
    tags: sgr

# Worker spark rules
